### PR TITLE
Update config.yml location

### PR DESCRIPTION
**Pull request by JordanPlayz158**
Changed the config.yml location from /var/lib/pterodactyl/config.yml to /srv/wings/config.yml (Most users are used to the config file being in the /srv/wings folder rather than the /var/lib/pterodactyl folder)

### CODE REVIEW

**Comment by parkervcp** [comment]
Honestly, if anything, I would say align with the linux standard and not our own by putting the config in `/etc/`.

**Comment by JordanPlayz158** [comment]
> 
> 
> Honestly, if anything, I would say align with the linux standard and not our own by putting the config in `/etc/`.

You make a fair point, we can change it to the linux standard like (/etc/wings/config.yml or /etc/pterodactyl/config.yml)

**Comment by DaneEveritt** [comment]
This is already correct, I'm not changing it back.

**Comment by schrej** [comment]
As stated on Discord as well, `/var/lib/pterodactyl` is not really correct, but neither is `/srv/wings`. It should be `/etc/wings/config.yaml` or `/etc/pterodactyl/wings.yaml`.

Regarding `/var/lib`, from the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html):
> 5.8.1. Purpose
> This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. **Users must never need to modify files in /var/lib to configure a package's operation**, and the specific file hierarchy used to store the data must not be exposed to regular users. [40]

**Comment by ghost** [comment]
> As stated on Discord as well, `/var/lib/pterodactyl` is not really correct, but neither is `/srv/wings`. It should be `/etc/wings/config.yaml` or `/etc/pterodactyl/wings.yaml`.
> 
> Regarding `/var/lib`, from the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html):
> 
> > 5.8.1. Purpose
> > This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. **Users must never need to modify files in /var/lib to configure a package's operation**, and the specific file hierarchy used to store the data must not be exposed to regular users. [40]

Should be `/etc/wings/config.yaml` in my opinion, the daemon is a software by it's own. For users who install both the panel and the daemon in the same server it might be confusing to have the configuration file for the daemon in a folder called `pterodactyl`.

**Comment by JordanPlayz158** [comment]
> 
> 
> > As stated on Discord as well, `/var/lib/pterodactyl` is not really correct, but neither is `/srv/wings`. It should be `/etc/wings/config.yaml` or `/etc/pterodactyl/wings.yaml`.
> > Regarding `/var/lib`, from the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html):
> > > 5.8.1. Purpose
> > > This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. **Users must never need to modify files in /var/lib to configure a package's operation**, and the specific file hierarchy used to store the data must not be exposed to regular users. [40]
> 
> Should be `/etc/wings/config.yaml` in my opinion, the daemon is a software by it's own. For users who install both the panel and the daemon in the same server it might be confusing to have the configuration file for the daemon in a folder called `pterodactyl`.

I support both Schrej's and Daniel's thinking!

**Comment by JordanPlayz158** [comment]
Updated config to agree with what Daniel and Schrej said and to adhere to the linux hierarchy and how it's suppose to be!

**Review by schrej — APPROVED** [review]

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/commit/fd83424ee2c986736a7a3f3f951571491bf4ee39 and https://github.com/pterodactyl/panel/commit/3b2e2c63c62f7df1846af193d5eea5e96259e0a6 with code to handle the new location and avoid an influx of "bugs" when this rolls out.

**Pull request closed without merging**
