### PR TITLE
Update docker-compose.example.yml

### PR DESCRIPTION
**Pull request by bobbyrc**
Adding a small note about the binding where server volumes live. I spent an afternoon trying to figure out why my servers were failing to install. Thought it may save someone else the trouble.

Thanks for the consideration!

### CODE REVIEW

**Comment by danny6167** [comment]
This really needs to specify why and how to make it work.
Its entirely possible to change the volume, but the path inside must match the outside

**Comment by bobbyrc** [comment]
Can you explain why both the inside and outside need to match? I attempted to bind the Pterodactyl-specific volumes to a `./data` directory in the same directory as the compose file. What I found was that there were then permissions issues with the `volumes` directory, likely because inside the container we are mapping to `/etc`.

Also happy to add more detail to the comment, but also didn't want to be too verbose in a comment in the compose file.

**Comment by matthewpi** [comment]
> Can you explain why both the inside and outside need to match? I attempted to bind the Pterodactyl-specific volumes to a `./data` directory in the same directory as the compose file. What I found was that there were then permissions issues with the `volumes` directory, likely because inside the container we are mapping to `/etc`.
> 
> Also happy to add more detail to the comment, but also didn't want to be too verbose in a comment in the compose file.

Because we use Docker to create containers on the host (outside of the container running Wings), the paths need to match.  If you configure the directory path on the panel for the node to be `/var/lib/pterodactyl/volumes` (as it is by default), Wings locally will look for files in that directory for the file manager, that will work with a mismatched host and container path.  However when we go to create a container, we will set the bind mount path to `/var/lib/pterodactyl/volumes/<server uuid>` which is looked up outside of the container on the host, which is why the containers fail to run.

**Comment by bobbyrc** [comment]
This definitely makes sense. I really appreciate you taking the time to explain that to me. Also super helpful for my own use. I updated the comments to reflect the requirement of the paths matching

**Pull request closed without merging**
