### PR TITLE
RPM is now tracking v1.5.3

### PR DESCRIPTION
**Pull request by ccallahan**

### CODE REVIEW

**Review by matthewpi — APPROVED** [review]

**Comment by ccallahan** [comment]
Just in the future, if someone could ping myself or @WaffleThief123 before or around release so we can update this, that would be awesome. Thanks!

**Comment by lucasvbeek** [comment]
Perhaps this could be automated with gh actions?

**Comment by trenutoo** [comment]
We should add this to the workflow and remove the changelog (thus making it easier) . RPM changelog is used for the RPM file itself and not for the service

**Comment by ccallahan** [comment]
> We should add this to the workflow and remove the changelog (thus making it easier) . RPM changelog is used for the RPM file itself and not for the service

Eh, there are some sysadms like me who tend to read the changelog before updating, and it doesn't take me more than two minutes to update it. But I do agree, this should be automated as best as possible, ideally keeping the changelog intact.

**Comment by trenutoo** [comment]
> > We should add this to the workflow and remove the changelog (thus making it easier) . RPM changelog is used for the RPM file itself and not for the service
> 
> Eh, there are some sysadms like me who tend to read the changelog before updating, and it doesn't take me more than two minutes to update it. But I do agree, this should be automated as best as possible, ideally keeping the changelog intact. 

It's actually considered a bad practice. RPM changelogs should be reserved for the packaging changes of RPM package itself, such as changing how it builds and not for updates of the software. Ideally the software changelog file should be shipped separately.

I can take a look into this on the weekend. This is definitely mundane task that should be automated in the release workflow. Probably add RPM spec file to release assets?

**Pull request merged**
