### PR TITLE
it's to its

### PR DESCRIPTION
**Pull request by camjac251**
Just a little grammar fix

### CODE REVIEW

**Comment by Zooma-a** [comment]
The grammar was correct before you changed it.

It's = contraction 
Its = possessive

**Comment by camjac251** [comment]
> The grammar was correct before you changed it.
> 
> It's = contraction
> Its = possessive

How I saw it was if, for example, you use it's then it must make sense as it is too. Here's an example I'll pull from https://github.com/pterodactyl/wings/pull/123/files#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fL82
This is what originally made me want to add this PR, when noticing it in the help menu on wings.

The original is
`pass in order to have wings generate and manage it's own SSL certificates using Let's Encrypt`
If I change it's to it is, it doesn't sound right.
`pass in order to have wings generate and manage it is own SSL certificates using Let's Encrypt`

I changed all of the ones that I thought needed it.
This was what I changed the above to in the PR
`pass in order to have wings generate and manage its own SSL certificates using Let's Encrypt`

**Comment by finnie2006** [comment]
The grammar is just right what you are doing is wrong

**Comment by camjac251** [comment]
> The grammar is just right what you are doing is wrong

**Comment by camjac251** [comment]
> The grammar is just right what you are doing is wrong

I double-checked to make sure maybe I made a mistake but Grammarly was also showing the same suggestion when giving it the above example. 
image

**Comment by parkervcp** [comment]
Technically only one of these was public facing but the others are fine too.

**Review by schrej — APPROVED** [review]

**Pull request merged**
