### PR TITLE
environment(docker): set outgoing ip correctly

### LINKED ISSUE #3841: Set the outgoing IP correctly when using multiple IPs on one node
### Describe the feature you would like to see.

By default docker always uses the first interface for outbound traffic. This can lead to issues with self-advertising servers like CS:GO as reported in #459.

### Describe the solution you'd like.

Docker has added support for a new label that allows to set the outbound IP of a docker network: https://github.com/moby/libnetwork/pull/2454

In order to support this we would need to create one docker network per IP address and assign the containers to the correct networks.

### Additional context to this request.

There is a hacky solution [here](https://github.com/pterodactyl/panel/issues/459#issuecomment-1003668331), but since it's now possible we should add support for the official one.

### PR DESCRIPTION
**Pull request by matthewpi**
Closes https://github.com/pterodactyl/panel/issues/3841

### CODE REVIEW

**Comment by brolpzt** [comment]
@matthewpi i will make a contribution on the subject: 

when you route the container this way you are limited by default to 32 bridge networks, this is a docker configuration.

you can change this setting by multiplying by 16x that number. to do this, configure your /etc/docker/daemon.json with these parameters:

```
{
    "default-address-pools": [
        {
            "base": "172.16.0.0/12",
            "size": 28
        },
        {
            "base": "192.168.0.0/16",
            "size": 24
        }
    ]
}
```

**Comment by matthewpi** [comment]
> @matthewpi i will make a contribution on the subject:
> 
> when you route the container this way you are limited by default to 32 bridge networks, this is a docker configuration.
> 
> you can change this setting by multiplying by 16x that number. to do this, configure your /etc/docker/daemon.json with these parameters:

I'm not too worried about this.  Most people don't have 32+ servers on the same node, let alone using the same egg that will have this option enabled.  Ideally we would just create a network with a `/24` or even smaller, because a `/16` (which I believe is the default), is way to excessive for what we need.

**Comment by brolpzt** [comment]
> > @matthewpi i will make a contribution on the subject:
> > when you route the container this way you are limited by default to 32 bridge networks, this is a docker configuration.
> > you can change this setting by multiplying by 16x that number. to do this, configure your /etc/docker/daemon.json with these parameters:
> 
> I'm not too worried about this. Most people don't have 32+ servers on the same node, let alone using the same egg that will have this option enabled. Ideally we would just create a network with a `/24` or even smaller, because a `/16` (which I believe is the default), is way to excessive for what we need.

No problem, anyway my contribution is for people who have the same problem.

**Comment by matthewpi** [comment]
> No problem, anyway my contribution is for people who have the same problem.

For now I'm gonna merge this, I feel more people are concerned about having this feature at all then potentially having issues regarding running out of subnets, which luckily there are workarounds for as you have mentioned.

**Comment by brolpzt** [comment]
Great

**Pull request merged**
