### PR TITLE
Add configurable server mounts

### PR DESCRIPTION
**Pull request by matthewpi**
This pull request adds support for configurable server mounts (requires https://github.com/pterodactyl/panel/pull/1915)

This works by adding additional `mount.Mount`s when creating a container for a server.

### CODE REVIEW

**Comment by schrej** [comment]
I think it should be configurable in the daemon config file which folders are allowed to be mounted. The default should be to disable mounts completely.
That way, if someone takes over the panel, it's harder to break into the daemon host system.

**Comment by DaneEveritt** [comment]
The more stuff you put in the daemon config the more problematic it becomes to keep everything updated when you have tons of systems though @schrej.

Plus, if you manage to break into the panel as an admin, you've already effectively gained a large amount of access to the system. I think security wise it might make more sense to have some defaults in the daemon that block mounting at any location within `/root`, `/etc`, `/var` and any other directories we think would be relevant.

I suppose we could also say all mounts _must_ be in `/home` or `/srv` or whatever the mount directory normally is. That would certainly keep things quite flexible, while also preventing someone from breaking in as an admin, and mounting `/` to all the servers or something.

I also agree that you should have a non-panel-togglable toggle in the daemon that enables mounts by default, but you can explicitly disable mounting in the configuration and just fail any requests that include the mount. I see this feature as highly requested, and I'd like to weigh the security implications of it without also making it a complete pain in the ass to use, especially for hosts.

**Comment by matthewpi** [comment]
I'd actually say to only allow `/mnt` (for external drives which might not be wanted) and `/srv`.  The daemon should also block the mounting of other servers or where the wings executable itself is located.  I didn't implement it because I was not sure what the best way to go around it would be.  I'll add a disabled by default config option that will only mount `/home/container`, preventing additional mounts from being loaded.

**Comment by parkervcp** [comment]
If a host is using an external mount point they should be mounting it in `/srv/` or `/home/` to work with the daemon at this point then. I am with Dane on this one, limiting it's reach is the best option.

**Comment by matthewpi** [comment]
> If a host is using an external mount point they should be mounting it in `/srv/` or `/home/` to work with the daemon at this point then. I am with Dane on this one, limiting it's reach is the best option.

What about external drives?  Why should `/home` be used?  If the user has the option to place the content anywhere it should be placed in a place not designed for system users to have their data stored (which can include other applications on the host system).  Technically the host path doesn't matter (as long as it is secure) as it should only matter where it is mounted inside of the container.

**Comment by parkervcp** [comment]
You can mount a device to where ever you want. `/home/pterodactyl/mounts/device` is a perfectly valid mount point.

We want to avoid any potential way to write to a system file. so `/mnt` is a bit broad for me.

**Comment by DaneEveritt** [comment]
I'd allow mnt, I use that all the time. I think it's best to start perhaps too strong on blocking and continue evaluating as time passes. Can always add a whitelist parameter to the config that is empty by default but can extend our default whitelist if needed. Would cover gaps while we figure out if it's a good one to include or not.

**Comment by schrej** [comment]
We could also allow `<data-dir>/shared` only by default, and allow to configure other paths in addition.

I don't really agree with the "hard to manage" part tbh. If you have that many nodes and aren't heavily using automation, that's on you.
We should rather look for things that are hard to automate and try to make them easier, e.g. adding a node to the panel. For example a reverse way of the current auto-config that requires remote url and api token and then allows to (interactively) register a node with the panel.

**Comment by matthewpi** [comment]
The only problem I see about putting this in the config file is ensuring that it cannot be updated by the panel, the whole point of this is to prevent nodes from being compromised if the panel is.

If we block all by default and have a whitelist then we can specify a few "safe" directories and people can configure them from there on their own terms.  I think only allowing `<data-dir>/shared` or `/srv/shared` would be a good default, any other directories such as `/mnt` and `/home` seem too broad and you should be required to be explicitly allow those directories, not to mention that you would have to be in the machine anyways to setup the files for a mount.

Also, due to the panel not having any knowledge of allowed directories, do I add a daemon endpoint for checking if a mount source directory is valid, or should any directory be "allowed" on the panel but have the daemon ignore it when creating a container?

**Pull request merged**
