### PR TITLE
Turn off the CGO to make it static linked

### PR DESCRIPTION
**Pull request by chisaato**

### CODE REVIEW

**Comment by pedxyuyuko** [comment]
relate to: https://github.com/pterodactyl/panel/issues/2671

**Comment by parkervcp** [comment]
This could have large sweeping affects.

I get that there is apparently an issue with alpine Linux somehow but I'm not sure what that actually is.

What little information we get from the other issue is lacking in information and doesn't convey the issue well.

**Comment by chisaato** [comment]
ok,let me explain it 

Alpine use musl as c lib, and it is not compatiable with glibc which is widly use in many linux distro.  
GitHub Release use ubuntu to build and enabling the CGO make it linked with the system c lib (glibc)  
so the binary can't excute in alpine container.

however the dockerfile use alpine to build, so the binary is linked with musl. it works fine with alpine.

if we turn off the CGO, the binary is static linked then it can work fine in alpine(musl) or other distro(glibc)

it is also good for those who need to build their own docker images.

**Comment by schrej** [comment]
If you want to build your own docker image, why not simply use a multi-stage build to make sure the binary is compatible?

**Comment by chisaato** [comment]
not just for custom docker image builders, make the binary independent with system dependencies is not a bad idea

**Comment by parkervcp** [comment]
The dockerfile packed into the repo is meant to be packed the way it is. I don't see how this is an issue. It has been working for those that have been using it.

I am not using the release from the repo. It's being built in an alpine container to run in an alpine container.

**Comment by DaneEveritt** [comment]
I believe their point is that the release build we make is only `glibc` compatible, and doesn't work with `musl`. I need to do some additional research to see what the implications of this specific change are, but I don't think it would really affect much, other than making the binary support even more systems?

**Comment by rxdn** [comment]
Correct me if I'm wrong, but this would build with statically linked SSL, no?
Heavily against this, for obvious reasons

**Comment by chisaato** [comment]
are there any disadvantage of static linked ssl？

**Comment by rxdn** [comment]
> are there any disadvantage of static linked ssl？

Yes - if there's another SSL vulnerability like heartbleed, you'd need to wait for a new wings binary to be released to patch it. Whereas with dynamically linked dependencies, you can just update your SSL library with your OS's package manager straight away.

**Comment by schrej** [comment]
> Yes - if there's another SSL vulnerability like heartbleed, you'd need to wait for a new wings binary to be released to patch it. Whereas with dynamically linked dependencies, you can just update your SSL library with your OS's package manager straight away.

Go has it's own ssl implementation, it doesn't rely on an external library. So if it is affected, you'd have to wait for a Go release anyway. And in case we don't manage to push out a binary in time if that should happen, you can also compile it yourself rather easily.

**Comment by rxdn** [comment]
> Go has it's own ssl implementation, it doesn't rely on an external library. So if it is affected, you'd have to wait for a Go release anyway. And in case we don't manage to push out a binary in time if that should happen, you can also compile it yourself rather easily.

TIL

**Comment by DaneEveritt** [comment]
Well, I have no proper experience here so I mean this looks & sounds fine to me?

**Comment by matthewpi** [comment]
From my experience I usually always disable CGO when building any of my projects unless they require it.  I'm not aware of such security implications or other potential downsides.

**Review by DaneEveritt — APPROVED** [review]

**Pull request merged**
